// <auto-generated />
namespace JAnet_ALlison_PHotography.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class picture52 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(picture52));
        
        string IMigrationMetadata.Id
        {
            get { return "201901250045425_picture52"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
